### PR TITLE
Handle deserialization failures in postMessage()

### LINKED ISSUE #1116: Remove StructuredCloneWithTransfer and add a messageerror event
Apologies for the churn. For SharedArrayBuffer we need to tweak serializing and deserializing a little further and unfortunately service worker is affected as well (you might have noticed another issue related to this as well and there might be some more coming).

https://github.com/whatwg/html/pull/2530 has the change to HTML and service workers will need to do something similar. Use StructuredSerializeWithTransfer and StructuredDeserializeWithTransfer separately and give each their own error handling.

### PR DESCRIPTION
**Pull request by domenic**
This is part of https://github.com/whatwg/html/pull/2530; see related links there for more information. Closes #1116.

It is on top of #1102, so that needs to be merged first. In addition, the HTML PR needs to be merged first so that the messageerror event type is actually defined somewhere; once that's done the Bikeshed HTML needs to be regenerated.

Also, this needs some tests, which I will write.

### CODE REVIEW

**Comment by jungkees** [comment]
Thanks @domenic. https://github.com/w3c/ServiceWorker/pull/1102 is merged.

**Comment by domenic** [comment]
Awesome. I'll rebase this and ping once we get https://github.com/whatwg/html/pull/2530 merged.

**Comment by domenic** [comment]
@jungkees this has been rebased on master and is ready to merge.

**Comment by jungkees** [comment]
Thanks @domenic! Great that you cleaned up the kill a worker references too.

**Comment by domenic** [comment]
Would someone be able to review https://github.com/w3c/web-platform-tests/pull/5628 ? It's pretty small, just testing the attribute reflection.

**Pull request merged**
