### PR TITLE
Editorial: more link-defaults and anchors cleanup

### PR DESCRIPTION
**Pull request by domenic**
I extracted out some more safe changes from #995. As you can see from the .html diff, there's not much difference; it's mostly just removing anchors blocks.

### CODE REVIEW

**Comment by jungkees** [comment]
@domenic, thanks for the cleanup!

Re: request's request and response's response, SW defines neither of them on its own. They actually reference fetch's Request object's request and Response object's response. So the current links are right. So that part of the anchors section can be removed too I think. I'll do that in the next commit.

**Comment by annevk** [comment]
Note that you don't always want to refer to the objects. You sometimes want the concepts.

**Comment by jungkees** [comment]
For the concepts, shouldn't I use for=/ ?

**Comment by annevk** [comment]
Yes, if you do that then you remove those lines and nothing should error.

**Pull request merged**
