### PR TITLE
reflect WG change [depends on another PR]

### PR DESCRIPTION
**Pull request by ylafon**
Depends on  tabatkins/bikeshed#1109

***
[Preview](https://s3.amazonaws.com/pr-preview/ylafon/ServiceWorker/master.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/ServiceWorker/d0df742...ylafon:6b4f6e3.html)

### CODE REVIEW

**Comment by jungkees** [comment]
@ylafon, could you put the same change to v1 file and commit it with the bikesheded HTMLs?

**Comment by ylafon** [comment]
Let's hope my bike shed install is correct. Here are the wanted edits.

**Comment by jakearchibald** [comment]
Thanks!

**Comment by jakearchibald** [comment]
I just ran bikeshed myself and got the same output, so it looks like your bikeshed install is indeed correct. Thanks @ylafon!

**Pull request merged**
