### PR TITLE
Editorial: export terms for Fetch

### PR DESCRIPTION
**Pull request by annevk**

### CODE REVIEW

**Comment by annevk** [comment]
I'm not sure what's going on with the generated HTML. It seems this repository is in some major need of bikeshed cleanup...

**Comment by domenic** [comment]
Probably should not be merged as-is due to the Bikeshed regressions. My initial guess is that the changes I asked @tabatkins to make to Bikeshed (which were lovely!) caused some regressions in Bikeshed that lost some of these internal links. Or, are you sure you have the latest Bikeshed + `bikeshed update`? It might be good to confirm by using the web service version and seeing if the output changes at all.

**Comment by annevk** [comment]
I'm pretty sure I'm on latest bikeshed. It started complaining a bit more about for= stuff.

**Comment by ylafon** [comment]
Marked as non-substantive for IPR from ash-nazg.

**Comment by jungkees** [comment]
@annevk, I cleaned up the bikesheld autolinks and incorporated the changes in this PR to that commit: https://github.com/w3c/ServiceWorker/commit/f17178badae7a8a3dd955bcc23b119b06ab36883 Please let me close this in favor of that. I'm still being accustomed to using bikeshed. Let me know if you need other changes for fetch.

**Comment by annevk** [comment]
Terms used in DOM also need to be exported. If you could do that, that would be great.

**Comment by jungkees** [comment]
Exported the terms used in DOM and HTML: https://github.com/w3c/ServiceWorker/commit/66a4fd9444b61c4d83567041e5fe36c592b2a22b

**Comment by annevk** [comment]
That's great, thanks!

**Pull request closed without merging**
