### PR TITLE
Remove duplicate step from "Update" algorithm

### PR DESCRIPTION
**Pull request by jugglinmike**
The `Service-Worker` header is appended to the request's header list in
a prior algorithm step.

### CODE REVIEW

**Comment by ylafon** [comment]
Marked as non-substantive for IPR from ash-nazg.

**Comment by jungkees** [comment]
Thanks @jugglinmike! The prior step was added when we added https://github.com/w3c/ServiceWorker/pull/1132/files#diff-27b79860afe28f01aed4f1f6228367faR2615 in a previous commit. I think we missed to remove the latter one.

I'd like to add you to the acknowledgement if you're fine. Would you let me know how I can write?

**Comment by jugglinmike** [comment]
> I'd like to add you to the acknowledgement if you're fine. Would you let me
> know how I can write?

That's very kind! You might want to double-check [the significance of my contributions](https://github.com/w3c/ServiceWorker/commits/master?author=jugglinmike), but if you insist, then you can add "Mike Pennisi" to the list.

**Comment by jungkees** [comment]
It's been of great help! Added: https://github.com/w3c/ServiceWorker/commit/a8d9e8717d70f149fed93c4d0b5fcd94bee392e8. Thanks.

**Comment by jugglinmike** [comment]
My pleasure :)

**Pull request merged**
