### PR TITLE
Update StructuredCloneWithTransfer() usage

### LINKED ISSUE #1089: Tweak StructuredCloneWithTransfer() usage
In https://github.com/whatwg/html/commit/97d644c97335956610a31e8ad98d1a388c063e84 we revised StructuredCloneWithTransfer() significantly. Although you are mostly protected from these changes, you need to change [[Clone]] to [[Deserialized]] and [[TransferList]] to [[TransferredValues]].

I can work on a PR for this sometime soon.

### PR DESCRIPTION
**Pull request by domenic**
Fixes #1089.

### CODE REVIEW

**Comment by mkruisselbrink** [comment]
Not entirely related to this PR, but the spec for ServiceWorker.postMessage looks not entirely correct. We call "Run Service Worker", which in parallel creates the workers global object, yet postMessage in the next step tries to synchronously access that global (which hasn't been created yet at that point). It seems instead postMessage should synchronously serialize the message, and then queue a task on the worker to actually deliver the message event after the worker has started up?

**Comment by jungkees** [comment]
Filed https://github.com/w3c/ServiceWorker/issues/1126.

I think we can merge this PR. @domenic, could you rebase it to resolve the conflict?

**Comment by domenic** [comment]
@jungkees updated

**Comment by jungkees** [comment]
Thanks!

**Pull request merged**
