### PR TITLE
Change the rest of the links to the new repo

### PR DESCRIPTION
**Pull request by anssiko**
@jungkees This will complement https://github.com/w3c/ServiceWorker/commit/eb7b112ac7055ff6afb4bb5a97ed72c4ac6c5c23 and updates the rest of the links (`s/slightlyoff/w3c/`).

### CODE REVIEW

**Comment by jungkees** [comment]
Thanks @anssiko! Could you s/issued/issues/ in "resolved issued marked needs spec" (originally mis-typed) and make it to the master branch?

**Comment by anssiko** [comment]
Thanks!

Assuming you've set the `master` branch as the GitHub Pages Source (via Settings > Options > GitHub Pages), I suggest you remove the `gh-pages` branch, and note in CONTRIBUTING.md the branch that should be used for contributions.

**Comment by marcoscaceres** [comment]
If we use the W3C's echidna, the spec can be auto-published to TR. We are trying to put an end to using gh-pages to see if we can make /TR/ be less garbage.

**Comment by annevk** [comment]
You're basically making TR/ more confusing then, though. Since then nobody can tell when it stands for trash and when it's useful. Would've been better to use a new namespace.

**Comment by marcoscaceres** [comment]
@annevk, I agree. Though canonical will be whatever Google, and other search enginesm (not the company) decide to return when people search for a spec. By killing the options available to one,  a new namespace might not matter as much because there will only be one source of truth (in a new namespace or on TRash).

**Pull request merged**
