### PR TITLE
Set default value of optional dictionary to {}

### PR DESCRIPTION
**Pull request by CYBAI**
This is part of heycam/webidl#758

heycam/webidl#750 introduces the change that use `{}` as default value for optional dictionaries.

***
<a href="https://pr-preview.s3.amazonaws.com/CYBAI/ServiceWorker/pull/1448.html" title="Last updated on Aug 9, 2019, 10:48 AM UTC (e4bf188)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/ServiceWorker/1448/7c07a47...CYBAI:e4bf188.html" title="Last updated on Aug 9, 2019, 10:48 AM UTC (e4bf188)">Diff</a>

### CODE REVIEW

**Comment by CYBAI** [comment]
Hmm, after checking other PRs in other w3c repos for updating default value of optional dictionary, I think I'm using the right syntax but I can't compile successfully locally as same as the Travis failure 🤔

**Comment by jakearchibald** [comment]
I guess we're blocked on https://github.com/tabatkins/bikeshed/issues/1491.

Happy to land this as soon as it builds. Thanks for the PR!

**Comment by CYBAI** [comment]
tabatkins/bikeshed#1491 is fixed! Let me close and reopen to trigger the CI again!

**Comment by jakearchibald** [comment]
Thanks for doing this! I've ported the changes to the v1 spec too.

**Pull request merged**
